### ISSUE TITLE
召集一些早期的众包合作开发者

### ISSUE THREAD

**Issue by cnblogs-team** [cnblogs/crowd#1]
第一批计划召集500名合作开发者

**Comment by cnblogs-team** [comment]
[博客园商业化之路-开发任务众包平台：召集早期合作开发者](https://www.cnblogs.com/cmt/p/18165432)

**Comment by yanluya** [comment]
我来了

**Comment by mrchipset** [comment]
Mark 一下，不知道会不会被Pick

**Comment by 15637454123** [comment]
这么怎么报名？

**Comment by tominyu** [comment]
nice to see you guys.

**Comment by 15637454123** [comment]
> nice to see you guys.
nice to meet you

**Comment by tangtaoit** [comment]
我来啦，即时通讯找我

**Comment by cnblogs-team** [comment]
第一批召集已完成，详见 [博客园商业化之路-众包平台：500位驭码好汉，等你来发单挑战](https://www.cnblogs.com/cmt/p/18188542)
